package pasienmodel

import "mylab-api-go/internal/database/eloquent"

func Schema() eloquent.Schema {
	return eloquent.Schema{
		Table:      "pasien",
		PrimaryKey: "kd_ps",
		Aliases: map[string]string{
			"company_id": "company_id",
			"com_id":     "company_id",
		},
		Columns: []string{
			"kd_ps",
			"nama_ps",
			"alamat",
			"telepon",
			"umur",
			"sec_id",
			"company_id",
			"jk",
			"tanggal",
			"tgl_lahir",
			"propinsi",
			"kota",
			"kecamatan",
			"kelurahan",
			"no_fax",
			"email",
			"info",
			"no_hp",
			"agama",
			"titel",
			"pekerjaan",
			"jabatan",
			"referensi",
			"acara",
			"viv_card",
			"nik_name",
			"pnc_customer_type_id",
			"pnc_vip_date",
			"pnc_vip_expired_date",
			"pnc_membership_update",
			"pnc_card_expired_date",
			"pnc_tgl_mitra",
			"pnc_total_point",
			"pnc_accumulated_sales",
			"pnc_periodic_sales",
			"pnc_jual_type",
			"pnc_sync",
			"pnc_customer_id",
			"pnc_kaijo_id",
			"pnc_crs_id",
			"freelancer",
			"type_program",
			"doc_mitra",
			"pnc_outlet_id",
			"mitra_doc",
			"tempat_lahir",
			"kd_dr",
			"departemen",
			"no_mrlama",
			"sts_alergi",
			"asuransi",
			"no_asuransi",
			"pendidikan",
			"penanggung_jawab",
			"lokasi_kerja",
			"status_karyawan",
			"ket_pekerjaan",
			"posisi_kerja_4",
			"sec_id_1",
			"lokasi_mcu",
			"gambar",
			"ket_gambar",
			"warga_negara",
			"sts_nikah",
			"sts_umur",
			"created_at",
			"updated_at",
			"sts_default",
			"custome_filename",
			"kelas_trafic",
			"faskes_asal",
			"kd_paket",
			"nik",
			"passport",
			"goldar",
		},
		Casts: map[string]eloquent.CastType{
			"kd_ps":                   eloquent.CastString,
			"nama_ps":                 eloquent.CastString,
			"alamat":                  eloquent.CastString,
			"telepon":                 eloquent.CastString,
			"umur":                    eloquent.CastString,
			"sec_id":                  eloquent.CastString,
			"company_id":              eloquent.CastInt,
			"jk":                      eloquent.CastString,
			"tanggal":                 eloquent.CastDateTime,
			"tgl_lahir":               eloquent.CastDateTime,
			"propinsi":                eloquent.CastString,
			"kota":                    eloquent.CastString,
			"kecamatan":               eloquent.CastString,
			"kelurahan":               eloquent.CastString,
			"no_fax":                  eloquent.CastString,
			"email":                   eloquent.CastString,
			"info":                    eloquent.CastString,
			"no_hp":                   eloquent.CastString,
			"agama":                   eloquent.CastString,
			"titel":                   eloquent.CastString,
			"pekerjaan":               eloquent.CastString,
			"jabatan":                 eloquent.CastString,
			"referensi":               eloquent.CastString,
			"acara":                   eloquent.CastString,
			"viv_card":                eloquent.CastString,
			"nik_name":                eloquent.CastString,
			"pnc_customer_type_id":     eloquent.CastString,
			"pnc_vip_date":             eloquent.CastDateTime,
			"pnc_vip_expired_date":     eloquent.CastDateTime,
			"pnc_membership_update":    eloquent.CastDateTime,
			"pnc_card_expired_date":    eloquent.CastDateTime,
			"pnc_tgl_mitra":            eloquent.CastDateTime,
			"pnc_total_point":          eloquent.CastInt,
			"pnc_accumulated_sales":    eloquent.CastInt,
			"pnc_periodic_sales":       eloquent.CastInt,
			"pnc_jual_type":            eloquent.CastString,
			"pnc_sync":                 eloquent.CastString,
			"pnc_customer_id":          eloquent.CastString,
			"pnc_kaijo_id":             eloquent.CastString,
			"pnc_crs_id":               eloquent.CastString,
			"freelancer":               eloquent.CastString,
			"type_program":             eloquent.CastString,
			"doc_mitra":                eloquent.CastString,
			"pnc_outlet_id":            eloquent.CastString,
			"mitra_doc":                eloquent.CastString,
			"tempat_lahir":             eloquent.CastString,
			"kd_dr":                    eloquent.CastString,
			"departemen":               eloquent.CastString,
			"no_mrlama":                eloquent.CastString,
			"sts_alergi":               eloquent.CastString,
			"asuransi":                 eloquent.CastString,
			"no_asuransi":              eloquent.CastString,
			"pendidikan":               eloquent.CastString,
			"penanggung_jawab":         eloquent.CastString,
			"lokasi_kerja":             eloquent.CastString,
			"status_karyawan":          eloquent.CastString,
			"ket_pekerjaan":            eloquent.CastString,
			"posisi_kerja_4":           eloquent.CastString,
			"sec_id_1":                 eloquent.CastString,
			"lokasi_mcu":               eloquent.CastString,
			"gambar":                   eloquent.CastString,
			"ket_gambar":               eloquent.CastString,
			"warga_negara":             eloquent.CastString,
			"sts_nikah":                eloquent.CastString,
			"sts_umur":                 eloquent.CastString,
			"created_at":               eloquent.CastDateTime,
			"updated_at":               eloquent.CastDateTime,
			"sts_default":              eloquent.CastString,
			"custome_filename":         eloquent.CastString,
			"kelas_trafic":             eloquent.CastString,
			"faskes_asal":              eloquent.CastString,
			"kd_paket":                 eloquent.CastString,
			"nik":                      eloquent.CastString,
			"passport":                 eloquent.CastString,
			"goldar":                   eloquent.CastString,
		},
		Timestamps: true,
	}
}
